"""
    Errors

    syntax error : parser ----> must be resolved


    logical error :  ---> You must solve it.


    runtime error  ---> exception
    "
        un expected event caused the program to stop
        ---> You must this exception
    "


"""

# def sumnum(num1, num2):
#     print(num1*num2)
#
#
# sumnum(3,3)



print("=========== Hello world ====================")

print("--------------- test-----------------------")

# print(name)

# try:
#     print(name)
# except:
#     print("---- error happend while printing the variable name ")
#     name = input("please enter the value ")
#
#
# print("@  "*20)
#
# print(f"Hello {name}")

###################

# try:
#     # print(name)
#     print(10/0)
# except Exception as e :
#     # print("---- error happend while printing the variable name ")
#     print(e)
#     name = input("please enter the value ")
#
#
# print("@  "*20)
#
# print(f"Hello {name}")

####################################################
# name = 'Ahmed'
# try:
#     print(name)
# except Exception as e :
#     # print("---- error happend while printing the variable name ")
#     print(e)
#     name = input("please enter the value ")
# else:
#     print("@  "*20)
#
#     print(f"Hello {name}")


# ########################## finally

name = 'Ali'
try:
    print(name)
except Exception as e :
    # print("---- error happend while printing the variable name ")
    print(e)
    # name = input("please enter the value ")
else:
    print("@  "*20)

    print(f"Hello {name}")
finally:
    print("-----------------this block will be executed always -----------------")

print("-----------------this block will be executed always -----------------")




























